user:
  name: mike
  uid: 1000
  group: mike
  shell: /usr/bin/zsh

dotfiles:
  url: https://github.com/perryao/dotfiles.git
  destination: dotfiles
  rcup_flags: -fx README.md

base_packages:
  - base-devel
  - pacman-contrib
  - tmux
  - git
  - rsync
  - lsof
  - jq
  - dep
  - vagrant
  - terraform

editors:
  - vim

base_fonts:
  - terminus-font
  - cantarell-fonts
  - noto-fonts
  - ttf-dejavu
  - ttf-liberation
  # - ttf-symbola
  - gsfonts
  - tex-gyre-fonts
  - ttf-droid
  - ttf-ubuntu-font-family
  - ttf-inconsolata
  - otf-font-awesome # for i3 workspace icons

aur_fonts:
  - ttf-signika
  - ttf-quintessential
  - ttf-oswald
  - ttf-opensans
  - ttf-merriweather-sans
  - ttf-merriweather
  - ttf-carlito
  - ttf-caladea
  - ttf-courier-prime
  - ttf-heuristica

docker_package: docker
docker_users:
  - mike

go_get:
  - 
