---
- name: download and unpack go
  unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Create system go group
  group: name=golang state=present

- name: Add user to system golang group
  user: name={{ user.name }} groups=golang append=yes
  tags:
    - user

# create a go workspace directory if it doesn't exist
- name: create go workspace
  file:
    path: /home/{{ user.name }}/go
    state: directory
    owner: "{{ user.name }}"
    mode: 0755

- name: "Go-Lang | Run get commands"
  shell: "/usr/local/go/bin/go get -u {{ item }}"
  environment:
    GOPATH: "{{ GOPATH }}"
  with_items: "{{ go_get }}"
  changed_when: false
  tags:
    - go_get
