---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xrandr
  pacman: name=xorg-xrandr state=present

- name: Install xprop
  pacman: name=xorg-xprop state=present
