---
- name: Install Firefox
  pacman: name=firefox-developer-edition state=present
  tags:
    - firefox

- name: Install Chromium
  pacman: name=chromium state=present
  tags:
    - chromium

- name: Install Chrome
  aur: name=google-chrome user={{ user.name }}
  tags:
    - chrome
